# 配置文件，在这里填写api

weatherXinZhi: SeSI8hL-BdFhE9MKb #心知天气api   从https://www.seniverse.com/注册获取
sauceno-api: b1f01f8db1c4eaf20 #sauceno搜图api，你可以从https://saucenao.com/user.php注册并获取
moderate: 1f8f8a82c68afeab   #色图审核api 从https://www.moderatecontent.com/获取
siZhiAi: #思知ai    从https://console.ownthink.com/login
- xxx
nasa_api: HSSpKddu2tdmM           # nasa相关天文api 从https://api.nasa.gov/index.html#main-content申请
e-hentai: ipb_session_id=bc46d5c21d; ipb_member_id=7584785; ipb_pass_hash=8e9aac17;sk=wo63 #抓取ehentai的cookies,方式https://pic-image-search.kituin.fun/wiki/picimagesearch/E-hentai/DataStructure/#cookies%E8%8E%B7%E5%8F%96
chatGLM: 69ef2489e.GxN2svpXi #chatGLM的apiKey，从https://open.bigmodel.cn/获取
gemini:
- AIzaSeyhw-lUKs3ecDg4IQ7CC31SXi5rNk
- xxx
cozi: https://xxxxxx.zeabur.app/v1/chat/completions  # https://github.com/avilliai/Manyana/issues/4
proxy: http://127.0.0.1:10809    #代理 自己设置对应的端口，没有就不填
bert_colab: https://mess-addressed-openings-exposed.trycloudflare.com/synthesize          #bert_vits_colab版本，不占用本地gpu，部署：https://colab.research.google.com/drive/1n8lI6pOiDtli2zC5fL9PZ9TZqbOafqma?usp=sharing 请注意，使用此功能必须配置上面的proxy项

