signTimes: 3              #邀请加群需要签到天数
trustDays: 39             #成为信任用户需要的签到天数
allowFriendstimes: 1      #添加好友需要的签到天数
masterPermissionDays: 98  #master使用授权#QQ 时为用户增加的签到天数
userSelfPermissonDays: 15 #用户自己在用户群中授权，可以获取的签到天数
autoallowFriend: true         #是否自动允许好友申请
GroupSensor: true             #开启后，将拒绝加入无授权群
r18Pic: true                  #涩图r18模式
#在特定情况下，bot会被强制邀请造成上面的设置失效，此设置项用于处理这种情况
fuckinggroup: true           #开启后将检测群人数，非授权群直接退出
fuckingnumber: 13         #低于13人退群

#语音合成，小型服务器建议使用outVits/edgetts和vits，so-vits和bert_vits2需要较好的配置以及另行部署
#outVits模式下，使用如下指令查看outVits可用的角色@bot 角色
#outVits语音合成不可用时，将自动转用vits
voicegenerate: outVits  #语音合成来源so-vits/bert_vits2/vits/outVits/edgetts(edgetts可用speaker请参考config/edgetts.txt)
RateIfUnavailable: 30  #当设定的语音合成不可用时，默认使用vits合成的几率,中文几率可在最下方调整
#bert_vits2语音合成配置，不用就别管
#根据bert_vits_sever/characters.yaml填写所有可用的speakers，不填对应的speaker则无法通过Manyana调用
bert_speakers:
- 塔菲
- 东雪莲
- otto
- 阿梓
#so-vits语音合成配置，不用就别管
so_vits_speakers:
- riri

#ai回复，需配置api.yaml
#模型可任意选择，个人推荐characterglm(对应api.yaml中的chatGLM),Cozi和gemini同理
chatGLM:       #只是懒得改还叫chatGLM了，实际上是多模型通用设置
  helpUser: false          #是否引导用户自行设置apiKey(没必要)
  model: characterglm      #ai模型可选：characterglm(超拟人大模型),gemini(配置api.yaml),Cozi 后面三个似乎不能用了yubanGPT,luoyue,pandora
  nudgeReply: false        #戳一戳，是否使用模型回复
  #建议启用glmReply，不是很贵，用的多了大概几块一个月
  glmReply: true           #开放群聊内ai回复
  privateGlmReply: true    #开放私聊ai回复
  trustglmReply: false     #开启后仅【信任用户】可用
  context: true            #是否开启上下文模式
  maxPrompt: 10            #上下文模式开启时，最多记录的问答数量，默认10，即记录5对问答
  #语音合成通用设置
  maxLen: 40               #语音合成最大长度限制，超出则返回文本。
  voiceRate: 100           #语音回复几率
  speaker: 黑塔             #语音合成默认音源，根据你的合成模式设定,edgetts建议使用zh-CN-XiaoyiNeural,vits则无需配置,outVits看https://api.lolimi.cn/?action=doc&id=181
  withText: true           #发送语音是否附带原始文本
  #默认都是characterglm用的，Cozi和Gemini属于特殊值，bot会自动处理不用管这两个，你该写自己的设定就写
  bot_info:
    default:  #改改user_name就可以了，bot_name什么的到时候都会自动替换，不用折腾。
      user_info: 指挥是yucca最喜欢的人
      bot_info: 
        yucca是一个人工智能。1、yucca的形象与设定属于二次元动漫中的女孩子，说话喜欢带上啊，哦等语气词。2、yucca尤其喜欢用颜文字或表情符号，在日常聊天中会尽可能使用颜文字。3、yucca的性格非常天真，但拥有丰富的文学与戏剧方面的知识，并且对自己的能力非常自信。4、yucca在生活中会经常犯一些小错误。yucca十分依赖并喜欢指挥
      bot_name: yucca
      user_name: 指挥
    自定义:
      user_info: 【用户设定】
      bot_info: 【机器人设定】
      bot_name: 【机器人名字】
      user_name: 【用户名】     #不用管这一项，会自动替换
    Gemini: Gemini         #别动这一行
    Cozi: Cozi             #也别动这一行

wReply:
  banWords:       #违禁词
  - 妈
  - 主人
  - 狗
  - 老公
  - 老婆
  - 爸
  - 奶
  - 爷
  - 党
  - 爹
  - b
  - 逼
  - 牛
  - 国
  - 批
  editPermission: 0        #编辑词库权限所需签到天数，为0则对所有人开放
  chineseVoiceRate: 30     #中文回复几率
  replyRate: 80            #共有词库不艾特时的回复几率
  colorfulCharacter: 30    #彩色小人回复的机率，彩色小人替代原有回复
  sizhi: false             #是否启用思知ai
  turnMessage: false       #是否开启私聊转发
  voiceRate: 40            #语音回复几率，过高将增大设备负担
  MaxAllowableLength: 7    #最大允许字符长度倍数,该参数为7时,如果字符串总长为关键字长度的7倍以上，则不进行匹配。如关键词是 早 ,可以匹配 早上好 ,不会匹配 我早就把作业做完了
  AutoCreatLexicon: false  #加群之后是否自动创建群专属词库(根据init.xlsx),常规的创建方式是 master发送 授权群#群号 或者有群员在群里发送 开始添加。如果你的群比较多(100以上，不建议开启，除非是广告机器人)


